"""Run basic_analytics.sql on Bronze via DuckDB, output Markdown report."""

import re
import sys
from datetime import datetime

import duckdb

from src.paths import BRONZE_DIR, DOCS_DIR, PROJECT_ROOT, SQL_DIR

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

SQL_FILE = SQL_DIR / "basic_analytics.sql"
REPORT = DOCS_DIR / "basic_analytics_report.md"


def first_keyword(stmt: str) -> str:
    """Return first SQL keyword, skipping leading -- comment lines."""
    for line in stmt.splitlines():
        line = line.strip()
        if not line or line.startswith("--"):
            continue
        return line.split(None, 1)[0].upper()
    return ""


def statement_label(stmt: str) -> str | None:
    """Extract label from '-- name: ...' comment if present."""
    m = re.search(r"--\s*name:\s*(.+)", stmt)
    return m.group(1).strip() if m else None


def main() -> None:
    con = duckdb.connect()
    tx_glob = (BRONZE_DIR / "raw_transactions" / "*.parquet").as_posix()
    merchants = (BRONZE_DIR / "raw_merchants" / "raw_merchants.parquet").as_posix()
    con.execute(f"CREATE VIEW bronze_transactions AS SELECT * FROM read_parquet('{tx_glob}')")
    con.execute(f"CREATE VIEW bronze_merchants AS SELECT * FROM read_parquet('{merchants}')")

    md = [
        "# Phân tích cơ bản trên Bronze (Day 4)",
        "",
        f"> Auto-generated by `src/analytics/run_basic_analytics.py` at "
        f"{datetime.now():%Y-%m-%d %H:%M:%S}.",
        "> Source: `sql/basic_analytics.sql` run on Bronze Parquet via DuckDB.",
        "",
    ]

    statements = [s.strip() for s in SQL_FILE.read_text(encoding="utf-8").split(";") if s.strip()]
    for stmt in statements:
        kw = first_keyword(stmt)
        if kw in ("CREATE", "SET", "DROP"):
            con.execute(stmt)  # setup, không in
            continue
        if kw in ("SELECT", "WITH"):
            label = statement_label(stmt) or "query"
            df = con.execute(stmt).df()
            table = df.to_string(index=False)
            # In ra console (giữ nguyên hành vi cũ)...
            print(f"\n===== {label} =====")
            print(table)
            # ...và gom vào báo cáo: bảng đặt trong khối ``` để giữ canh cột, không phụ thuộc tabulate.
            md += [f"## {label}", "", f"*{len(df)} dòng*", "", "```", table, "```", ""]

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(md), encoding="utf-8")
    print(f"\n>> Đã ghi báo cáo: {REPORT.relative_to(PROJECT_ROOT).as_posix()}")


if __name__ == "__main__":
    main()
